{
 "title": "Solar Home",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Production and Consumption",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "ChargeLevel",
     "measurement": "varta",
     "query": "SELECT SOC_GS FROM \"varta\" WHERE (\"location\" = 'C1') AND $timeFilter",
     "select": [
      [
       { "params": [ "CapRemain" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "B1M1" }
     ]
    },
    {
     "alias": "Battery In/Out",
     "measurement": "varta",
     "query": "SELECT ( \"IInselL1\"  * \"UInselL1\" +  \"IInselL2\"  * \"UInselL2\" +  \"IInselL3\"  * \"UInselL3\" ) /100 FROM \"varta\" WHERE (\"location\" = 'WR1') AND $timeFilter\n",
     "select": [
      [
       { "params": [ "IVerbundL1" ], "type": "field" },
       { "params": [ " /100" ], "type": "math" }
      ],
      [
       { "params": [ "UVerbundL1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "WR1" }
     ]
    },
    {
     "alias": "Grid In/Out",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "varta",
     "query": "SELECT ( \"IVerbundL1\"  * \"UVerbundL1\" +  \"IVerbundL2\"  * \"UVerbundL2\" +  \"IVerbundL3\"  * \"UVerbundL3\" ) /100 FROM \"varta\" WHERE (\"location\" = 'WR1') AND $timeFilter",
     "select": [
      [
       { "params": [ "UInselL1" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "WR1" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV Source",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "PV_DC_W" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "inverter",
     "query": "SELECT \"Home_consumption_solar\"+\"Home_consumption_grid\" FROM \"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Home_consumption_solar" ], "type": "field" },
       { "params": [ "Home Consumption" ], "type": "alias" }
      ],
      [
       { "params": [ "Home_consumption_grid" ], "type": "field" },
       { "params": [ "GridConsumption" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "measurement": "varta",
     "query": "SELECT (last(\"UInselL1\") + last(\"UInselL2\") + last(\"UInselL3\"))/3 as Spannung, (last(\"IVerbundL1\")+ last(\"IVerbundL2\")+last(\"IVerbundL3\"))/30 as Charging, last(\"SOC_GS\") as Capacity, ( last(\"TempL1\") + last(\"TempL1\") + last(\"TempL1\") ) / 3 as Temperatur FROM \"varta\"",
     "select": [
      [
       { "params": [ "UInselL1" ], "type": "field" }
      ],
      [
       { "params": [ "UInselL2" ], "type": "field" }
      ],
      [
       { "params": [ "UInselL3" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "WR1" }
     ]
    }
   ]
  },
  {
   "title": "State of Charge",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "varta",
     "select": [
      [
       { "params": [ "SOC_GS" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lüfter",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "varta",
     "select": [
      [
       { "params": [ "Luefter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Freqency",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "targets": [
    {
     "measurement": "varta",
     "select": [
      [
       { "params": [ "FNetz" ], "type": "field" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "varta",
     "select": [
      [
       { "params": [ "TempL1" ], "type": "field" }
      ],
      [
       { "params": [ "TempL2" ], "type": "field" }
      ],
      [
       { "params": [ "TempL3" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "WR1" }
     ]
    },
    {
     "alias": "Chgr.",
     "measurement": "varta",
     "query": "SELECT \"TBoard\" FROM \"varta\" WHERE (\"location\" = 'C1') AND $timeFilter",
     "select": [
      [
       { "params": [ "TBoard" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "C1" }
     ]
    },
    {
     "alias": "Brd.",
     "groupBy": [
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "varta",
     "select": [
      [
       { "params": [ "TBoard" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "WR1" }
     ]
    },
    {
     "alias": "Rack",
     "measurement": "varta",
     "query": "SELECT \"Temp_Rack\"  / 10, \"TempAvg\"  / 10 FROM \"varta\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Temp_Rack" ], "type": "field" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Avg",
     "measurement": "varta",
     "query": "SELECT \"Temp_Rack\"  / 10, \"TempAvg\"  / 10 FROM \"varta\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "TempAvg" ], "type": "field" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "varta",
     "select": [
      [
       { "params": [ "SystemState" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Yield",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "DailyYield",
     "measurement": "inverter",
     "query": "SELECT \"Day_yield_Wh\" FROM \"inverter\" WHERE time >= now() - 30d",
     "select": [
      [
       { "params": [ "Day_yield_Wh" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}